# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"Base": "codeforces_python_client.ipynb",
         "Contest": "codeforces_python_client.ipynb",
         "User": "codeforces_python_client.ipynb",
         "Problem": "codeforces_python_client.ipynb",
         "UserRating": "codeforces_python_client.ipynb",
         "BlogEntry": "codeforces_python_client.ipynb",
         "Comment": "codeforces_python_client.ipynb",
         "Party": "codeforces_python_client.ipynb",
         "ProblemStatistics": "codeforces_python_client.ipynb",
         "ProblemResult": "codeforces_python_client.ipynb",
         "RecentAction": "codeforces_python_client.ipynb",
         "Hack": "codeforces_python_client.ipynb",
         "Submission": "codeforces_python_client.ipynb",
         "RanklistRow": "codeforces_python_client.ipynb",
         "Standings": "codeforces_python_client.ipynb",
         "CFApi": "codeforces_python_client.ipynb"}

modules = ["core.py"]

doc_url = "https://geekypandey.github.io/co_py/"

git_url = "https://github.com/geekypandey/co_py/tree/main/"

def custom_doc_links(name): return None
