# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"CFApi": "00_core.py.ipynb",
         "cf": "00_core.py.ipynb",
         "contests": "00_core.py.ipynb",
         "contest": "00_core.py.ipynb",
         "Base": "01_types.py.ipynb",
         "Contest": "01_types.py.ipynb",
         "Problem": "01_types.py.ipynb",
         "ProblemStatistics": "01_types.py.ipynb",
         "User": "01_types.py.ipynb",
         "UserRating": "01_types.py.ipynb",
         "BlogEntry": "01_types.py.ipynb",
         "Comment": "01_types.py.ipynb",
         "Party": "01_types.py.ipynb",
         "ProblemResult": "01_types.py.ipynb",
         "RecentAction": "01_types.py.ipynb",
         "Submission": "01_types.py.ipynb",
         "RanklistRow": "01_types.py.ipynb",
         "Standings": "01_types.py.ipynb",
         "Hack": "01_types.py.ipynb",
         "RatingChange": "01_types.py.ipynb"}

modules = ["core.py",
           "types.py"]

doc_url = "https://geekypandey.github.io/co_py/"

git_url = "https://github.com/geekypandey/co_py/tree/master/"

def custom_doc_links(name): return None
